services:
  app:
    build: .
    image: your-nestjs-app-image  # Replace this with your app's Docker image
    ports:
      - "3000:3000"  # Expose port 3000 from the container to your local machine
    environment:
      - DB_HOST=mysql  # Docker service name for MySQL
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - APP_PORT=${APP_PORT}
    env_file:
      - .env
    depends_on:
      - mysql  # Ensures the MySQL service starts before the app

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}  # Set the database name to be created
      - MYSQL_USER=root  # Set the non-root user
      - MYSQL_PASSWORD=root # Set the password for the non-root user
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql  # Persist MySQL data in a Docker volume
    ports:
      - '3306:3306'  # Expose MySQL port

volumes:
  mysql:

networks:
  default:
    driver: bridge
